# Nombre webapp
spring.application.name=productosrest01

# --- Base de datos H2 en memoria ---
spring.datasource.url=jdbc:h2:mem:productos;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- Iniciar siempre scripts SQL al arrancar ---
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.data-locations=classpath:productosrest.sql

# --- Configuración JPA ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# --- Consola web H2 ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Api versioning ---
api.version=v1

server.port=8080